spring.application.name=nasa-backend
nasa.api.key=ROHvBhWvqefv4pNrU4c3SndWRSgsb7mcFwcg6ESO
nasa.api.url=https://api.nasa.gov/EPIC/api/natural
spring.datasource.url=jdbc:postgresql://localhost:5432/student_tabel
spring.datasource.username=postgres
spring.datasource.password=Montu7890#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.name=admin
spring.security.user.password=admin123
jwt.secret=jisfus580415484sfuyefs1f05es80fs8e4fs84fs85ef14s8f4se81f8s6e4sf48es4fs85e4f85s4f0
jwt.expiration=86400000
